### PR TITLE
Forbid Zero-sized types from deserialization

### LINKED ISSUE #19: BorshDeserialize can cause UB by copying zero sized objects with no safe Copy impl
Repro:

```rust
mod singleton {
    use std::sync::atomic::{AtomicBool, Ordering};

    // Important: no Copy or Clone impl
    pub struct Handle(());

    impl Handle {
        pub fn get() -> Self {
            static EXISTS: AtomicBool = AtomicBool::new(false);
            if EXISTS.swap(true, Ordering::Relaxed) {
                panic!("one singleton handle has already been created");
            } else {
                Handle(())
            }
        }

        // Proof of exclusive access to a handle grants exclusive access to some
        // corresponding underlying state. It's guaranteed that at most one
        // handle exists in the entire program so this is sound.
        pub fn access(&mut self) -> &mut State {
            static mut STATE: State = None;
            unsafe { &mut STATE }
        }
    }

    type State = Option<String>;
}

use borsh::BorshDeserialize;
use std::io::Result;

struct Wrap(singleton::Handle);

impl BorshDeserialize for Wrap {
    fn deserialize(_buf: &mut &[u8]) -> Result<Self> {
        Ok(Wrap(singleton::Handle::get()))
    }
}

fn main() {
    let mut x = Vec::<Wrap>::deserialize(&mut &[2, 0, 0, 0][..]).unwrap();
    let (first, rest) = x.split_first_mut().unwrap();
    *first.0.access() = Some("...................".to_owned());
    let s = rest[0].0.access().as_mut().unwrap();
    *first.0.access() = None;
    println!("{}", s);
}
```

The result is segfault or other corruption:

```console
$ cargo run --release
Segmentation fault (core dumped)

$ cargo run
thread 'main' panicked at 'failed printing to stdout: Bad address (os error 14)', library/std/src/io/stdio.rs:940:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### LINKED ISSUE #52: Zero Sized Types should not enable DoS
We currently special-case zst's when deserializing vectors: 

https://github.com/near/borsh-rs/blob/b03a03c4b876782e2e870ee3c714ea569b774026/borsh/src/de/mod.rs#L282-L293

I think the reason to do that is to avoid DOS attacks. If we remove this restriction, then it's possible to hand-craft four-byte-len `vec![(); !0]`, which will take a lot of time to deserialize. There are a couple of problems with this approach though:

* it is unsound (#19)
* it doesn't' fully address the problem (we have the same issue for hash maps)

### PR DESCRIPTION
**Pull request by iho**
Resolves [RUSTSEC-2023-0033](https://github.com/ipvm-wg/homestar/issues/127)
Resolves #19 
Resolves #52

### CODE REVIEW

**Review by frol — CHANGES_REQUESTED** [review]
@iho Thanks for working on it! There are a couple of things:

* [x] Test needs to be fixed (CI failed due to unused import in the test file)
* [ ] Let's also fail on the serialization of Vec<ZST>, so there is symmetry and developers could catch errors (unfortunately, it seems there is no way to make the implementation generic over Vec<non-ZST> in Rust, so we cannot catch it at compile time) - add/update a test for it as well

File: borsh/src/ser/mod.rs [hunk 1]
```diff
@@ -267,6 +268,12 @@ where
 {
     #[inline]
     fn serialize<W: Write>(&self, writer: &mut W) -> Result<()> {
+        if size_of::<T>() == 0 {
+            return Err(Error::new(
+                ErrorKind::InvalidInput,
+                "Zero-sized types are not allowed.",
```
Comment (frol) [inline borsh/src/ser/mod.rs:274]: I feel this might be more helpful to the developers:

```suggestion
                "Vectors of zero-sized types are not allowed due to deny-of-service concerns on deserialization.",
```

File: borsh/src/de/mod.rs [hunk 2]
```diff
@@ -377,21 +377,18 @@ where
 {
     #[inline]
     fn deserialize_reader<R: Read>(reader: &mut R) -> Result<Self> {
+        if size_of::<T>() == 0 {
+            return Err(Error::new(
+                ErrorKind::InvalidInput,
+                "Zero-sized types are not allowed.",
```
Comment (frol) [inline borsh/src/de/mod.rs:383]:
```suggestion
                "Vectors of zero-sized types are not allowed due to deny-of-service concerns on deserialization.",
```

File: borsh/tests/test_zero_size.rs [hunk 3]
```diff
@@ -1,11 +1,35 @@
+use borsh::to_vec;
 use borsh::BorshDeserialize;
-
-#[derive(BorshDeserialize, PartialEq, Debug)]
-struct A;
+use borsh::BorshSerialize;
+#[derive(BorshDeserialize, BorshSerialize, PartialEq, Debug)]
```
Comment (frol) [inline borsh/tests/test_zero_size.rs:4]: Let's add an empty line here

```suggestion

#[derive(BorshDeserialize, BorshSerialize, PartialEq, Debug)]
```

**Review by frol — APPROVED** [review]
@iho Thanks for the PR!

**Comment by maxammann** [comment]
Great! As soon as a release is published I will make sure that the RustSec advisory is updated.

**Comment by paolobarbolini** [comment]
Looks like a release was made just a few days before this getting merged. Are we going to get a new release soon?

**Comment by iho** [comment]
@paolobarbolini I guess we will make release this week when I finish my PR and another one(pretty small).
