### PR TITLE
fix: unused fields warn, fields for inner structs of derived BorshSch…

### LINKED ISSUE #111: Cloned enum struct variant fields are reported as unused
Take this example:

```rust
use near_sdk::borsh::{self, BorshSchema};

#[derive(BorshSchema)]
pub enum A {
    B {
        c: (),
    },
}
```

Rust reports:

```console
warning: field `c` is never read
  --> src/lib.rs:12:9
   |
3  | #[derive(BorshSchema)]
   |          ----------- field in this struct
...
6  |         c: (),
   |         ^
   |
   = note: `#[warn(dead_code)]` on by default
```

Removing the derive, the warning goes away.

This is somewhat related to https://github.com/near/borsh-rs/issues/110, where `BorshSchema` clones the `A::B` path into a struct `AB`, for which it then derives `BorshSchema`.

```rust
#[derive(BorshSchema)]
struct AB {
    c: (),
}
```

Looking at this, it's easier to see why rust reports an unread variable.

### PR DESCRIPTION
**Pull request by dj8yfo**
…ema method

Resolves #111 
An example of [repro](https://github.com/dj8yfo/dead_code_borsh_derive)

### CODE REVIEW

File: borsh-schema-derive-internal/src/enum_schema.rs [hunk 1]
```diff
@@ -96,6 +96,7 @@ pub fn process_enum(input: &ItemEnum, cratename: Ident) -> syn::Result<TokenStre
             }
         }
         anonymous_defs.extend(quote! {
+            #[allow(dead_code)]
```
Comment (frol) [inline borsh-schema-derive-internal/src/enum_schema.rs:99]: @dj8yfo I don't have all the necessary context here, so I would ask you to look into it: do we even need those unused fields in the struct? I somehow feel uneasy about silencing the compiler here as it might indicate that something is missing / not implemented when it should be.

Comment (dj8yfo) [reply borsh-schema-derive-internal/src/enum_schema.rs:99]: I've looked into it.
The fields with their types and possibly `#[borsh_skip]` attributes are needed to derive correct inner impl `BorshSchema` for inner struct inside of method of `BorshSchema` impl for enum. So that type info is still needed.
The compiler is complaining that these structs never get constructed and their fields read. 
Which is kind of normal, provided that the structs are [invisible](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1c3059950fbd7fc81a32611ba27eec97) outside of the [method's scope](https://github.com/near/borsh-rs/blob/master/borsh-schema-derive-internal/src/enum_schema.rs#L155-L173). 
They're accessed by their types instead : `<InnerStruct>::declaration()`, `<InnerStruct as borsh::BorshSchema>::add_definitions_recursively(definitions)`.

**Review by frol — APPROVED** [review]

File: borsh-schema-derive-internal/src/enum_schema.rs (hunk 1 above)
Comment (frol) [reply borsh-schema-derive-internal/src/enum_schema.rs:99]: Thanks for looking into it!
