### PR TITLE
fix: filter out foreign attributes in `BorshSchema` derive for enum

### LINKED ISSUE #110: Schema does not clean unused attrs from cloned enum struct variants
```rust
use borsh::{self, BorshSchema};
use serde::Serialize;

#[derive(Serialize, BorshSchema)]
enum A {
    #[serde(rename = "ab")]
    B {
        #[serde(rename = "abc")]
        c: (),
    },
}
```

Roughly expands into:

```rust
enum A {
    #[serde(rename = "ab")]
    B {
        #[serde(rename = "abc")]
        c: (),
    },
}

impl borsh::BorshSchema for A {
    fn declaration() -> borsh::schema::Declaration {
        "A".to_string()
    }

    fn add_definitions_recursively(
        definitions: &mut borsh::maybestd::collections::HashMap<
            borsh::schema::Declaration,
            borsh::schema::Definition,
        >,
    ) {
        #[derive(BorshSchema)]
        struct AB {
            #[serde(rename = "abc")]
            c: (),
        }

        <AB as BorshSchema>::add_definitions_recursively(definitions);

        let variants = <[_]>::into_vec(
            #[rustc_box]
            ::alloc::boxed::Box::new([("B".to_string(), <AB>::declaration())]),
        );

        let definition = borsh::schema::Definition::Enum { variants };

        Self::add_definition(Self::declaration(), definition, definitions);
    }
}
```

As seen in the function `add_definitions_recursively`, the enum variant `A::B` is effectively cloned into a struct `AB`:

```rust
#[derive(BorshSchema)]
struct AB {
    #[serde(rename = "abc")]
    c: (),
}
```

Which, oddly, still retains any non-borsh attributes the origin had.

Causing builds to fail, because rust can't find a source for those attributes:

```console
$ cargo build
error: cannot find attribute `serde` in this scope
 --> src/lib.rs:8:11
  |
8 |         #[serde(rename = "abc")]
  |           ^^^^^
  |
  = note: `serde` is in scope, but it is a crate, not an attribute
```

### PR DESCRIPTION
**Pull request by dj8yfo**
Fixes #110

### CODE REVIEW

File: borsh-schema-derive-internal/src/enum_schema.rs [hunk 1]
```diff
@@ -45,6 +46,20 @@ pub fn process_enum(input: &ItemEnum, cratename: Ident) -> syn::Result<TokenStre
                     #ident ,
                 }
             });
+
+        match &mut anonymous_struct.fields {
+            Fields::Named(named) => {
+                for field in &mut named.named {
+                    field.attrs = filter_skip(&field.attrs);
```
Comment (frol) [inline borsh-schema-derive-internal/src/enum_schema.rs:53]: nit: There is `fields: variant.fields.clone(),` above, so you can use either of the three paths:

1. Instead of cloning `variant.fields` on construction, filter it out before `anonymous_struct` construction
2. Pass owned `field.attrs` instead of a reference, and use [`Vec::retain`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.retain)
3. Pass `&mut field.attrs`, don't return anything, and use [`Vec::retain`](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.retain)

File: borsh-schema-derive-internal/src/helpers.rs [hunk 2]
```diff
@@ -8,6 +8,19 @@ pub fn contains_skip(attrs: &[Attribute]) -> bool {
...
+pub fn filter_skip(attrs: &[Attribute]) -> Vec<Attribute> {
+    attrs
+        .iter()
+        .filter_map(|attr| {
+            if attr.path().to_token_stream().to_string().as_str() == "borsh_skip" {
+                Some(attr.clone())
+            } else {
+                None
+            }
+        })
```
Comment (frol) [inline borsh-schema-derive-internal/src/helpers.rs:20]: nit: `filter` + `cloned` looks easier than `filter_map`:

```suggestion
pub fn filter_skip(attrs: &[Attribute]) -> Vec<&Attribute> {
    attrs
        .iter()
        .filter(|attr| attr.path().to_token_stream().to_string() == "borsh_skip")
        .cloned()
```

**Review by frol — APPROVED** [review]
Overall, looks good to me, but I caught some small code-style items. Feel free to ignore the "nit" ones.
