### PR TITLE
fix: #[borsh_skip] on field of struct enum variant (BorshSerialize)

### LINKED ISSUE #173: `BorshSerialize` failure to compile derive with `#[borsh_skip]` on struct variant field
While resolving #110 , the following snippet fails to compile (in the `BorshSerialize` part). 
It must be more or less obvious bug, as derive of `BorshDeserialize` succeeds (as well as `BorshSerialize` for tuple struct variants).
```rust
use borsh::{self, BorshSerialize, BorshDeserialize};


#[derive(BorshDeserialize)]
enum AA {
    B {
        #[borsh_skip]
        c: i32,

        d: u32,
    },

    NegatedVariant {
        beta: u8,
    }
}

#[derive(BorshDeserialize)]
enum AAT {
    B(#[borsh_skip] i32, u32),

    NegatedVariant {
        beta: u8,
    }
}

#[derive(BorshSerialize)]
enum AATB {
    B(#[borsh_skip] i32, u32),

    NegatedVariant {
        beta: u8,
    }
}

#[derive(BorshSerialize)]
enum AATTB {
    B(#[borsh_skip] i32, #[borsh_skip] u32),

    NegatedVariant {
        beta: u8,
    }
}
// ERROR!
#[derive(BorshSerialize)]
enum AB {
    B {
        #[borsh_skip]
        c: i32,

        d: u32,
    },

    NegatedVariant {
        beta: String,
    }
}
// ERROR!
#[derive(BorshSerialize)]
enum AAB {
    B {
        #[borsh_skip]
        c: i32,

        #[borsh_skip]
        d: u32,
    },

    NegatedVariant {
        beta: String,
    }
}


fn main() {
    
}
```

```bash
 1  error: expected field pattern, found `_`
   --> src/main.rs:44:10
 2  error: expected `}`, found `c`
   --> src/main.rs:48:9
 3  error: proc-macro derive produced unparsable tokens
   --> src/main.rs:44:10
 4  error: expected field pattern, found `_`
   --> src/main.rs:58:10
 5  error: expected `}`, found `c`
   --> src/main.rs:62:9
 6  error: proc-macro derive produced unparsable tokens
   --> src/main.rs:58:10
 7  error[E0425]: cannot find value `d` in this scope
   --> src/main.rs:50:9

```

### PR DESCRIPTION
**Pull request by dj8yfo**
Resolves #173

### CODE REVIEW

**Comment by frol** [comment]
@dj8yfo Let's use `insta` crate for snapshot testing, see this issue on near-sdk-rs and my comment mentioned there: https://github.com/near/near-sdk-rs/issues/1038

**Comment by dj8yfo** [comment]
the actual fix is in this commit https://github.com/near/borsh-rs/pull/174/commits/fbe04fc9d48de93b54f0afcbf8a0187a4ac67c55

File: borsh-derive-internal/src/enum_ser.rs [hunk 1]
```diff
@@ -109,3 +80,196 @@ pub fn enum_ser(input: &ItemEnum, cratename: Ident) -> syn::Result<TokenStream2>
...
+            where_predicates.push(
+                syn::parse2(quote! {
+                    #field_type: #cratename::ser::BorshSerialize
+                })
+                .unwrap(),
+            );
+            variant_body.extend(quote! {
+                 #cratename::BorshSerialize::serialize(#field_name, writer)?;
+            })
+        }
```
Comment (frol) [inline borsh-derive-internal/src/enum_ser.rs:122]: This way it is easier to follow the logic.

Note, I also:
* replaced `dot_dot_pattern_match` with `has_skipped_fields` (in fact, I feel we can drop it, and unconditionally add `..` - it will work fine even if all the fields are named explicitly)
* renamed `field_name` to `field_ident` to align with the terminology used in the "unnamed_fields" function)

```suggestion
        if contains_skip(&field.attrs) {
            has_skipped_fields = true;
        } else {
            let field_ident = field.ident.clone().unwrap();
            variant_header.extend(quote! { #field_ident, });
            let field_type = &field.ty;
            where_predicates.push(
                syn::parse2(quote! {
                    #field_type: #cratename::ser::BorshSerialize
                })
                .unwrap(),
            );
            variant_body.extend(quote! {
                 #cratename::BorshSerialize::serialize(#field_ident, writer)?;
            })
        }
```

File: borsh-derive-internal/src/enum_ser.rs [hunk 2]
```diff
@@ -109,3 +80,196 @@ pub fn enum_ser(input: &ItemEnum, cratename: Ident) -> syn::Result<TokenStream2>
...
+) -> syn::Result<VariantParts> {
+    let mut where_predicates: Vec<WherePredicate> = vec![];
+    let mut variant_header = TokenStream2::new();
+    let mut variant_body = TokenStream2::new();
+    for (field_idx, field) in fields.unnamed.iter().enumerate() {
+        let field_idx = u32::try_from(field_idx).expect("up to 2^32 fields are supported");
+        if contains_skip(&field.attrs) {
+            let field_ident = Ident::new(format!("_id{}", field_idx).as_str(), Span::call_site());
+            variant_header.extend(quote! { #field_ident, });
+            continue;
```
Comment (frol) [inline borsh-derive-internal/src/enum_ser.rs:154]: Redundant:

```suggestion
```

File: borsh-derive-internal/src/enum_ser.rs [hunk 3]
```diff
@@ -109,3 +80,196 @@ pub fn enum_ser(input: &ItemEnum, cratename: Ident) -> syn::Result<TokenStream2>
...
+                    #field_type: #cratename::ser::BorshSerialize
+                })
+                .unwrap(),
+            );
+
+            let field_ident = Ident::new(format!("id{}", field_idx).as_str(), Span::call_site());
+            variant_header.extend(quote! { #field_ident, });
+            variant_body.extend(quote! {
+                #cratename::BorshSerialize::serialize(#field_ident, writer)?;
+            })
```
Comment (frol) [inline borsh-derive-internal/src/enum_ser.rs:168]: Let's align the order of blocks with the one in "named_fields":

```suggestion
            let field_ident = Ident::new(format!("id{}", field_idx).as_str(), Span::call_site());
            variant_header.extend(quote! { #field_ident, });
            let field_type = &field.ty;
            where_predicates.push(
                syn::parse2(quote! {
                    #field_type: #cratename::ser::BorshSerialize
                })
                .unwrap(),
            );
            variant_body.extend(quote! {
                #cratename::BorshSerialize::serialize(#field_ident, writer)?;
            })
```

**Review by frol — CHANGES_REQUESTED** [review]

**Comment by dj8yfo** [comment]
i've included change `Span::call_site` -> `Span::mixed_site` on three lines in [commit](https://github.com/near/borsh-rs/pull/174/commits/8438dd4fbdebfb40c2c51443f80e75bc0c44cfa6)

File: borsh-derive-internal/src/enum_ser.rs [hunk 4]
```diff
@@ -109,3 +80,192 @@ pub fn enum_ser(input: &ItemEnum, cratename: Ident) -> syn::Result<TokenStream2>
...
+
+            variant_body.extend(quote! {
+                 #cratename::BorshSerialize::serialize(#field_ident, writer)?;
+            })
+        }
+    }
+    // `..` pattern matching works even if all fields were specified
+    let dot_dot = syn::Token![..](Span::mixed_site());
+    variant_header.extend(quote! { #dot_dot });
+    variant_header = quote! { { #variant_header }};
```
Comment (frol) [inline borsh-derive-internal/src/enum_ser.rs:122]: @dj8yfo Can you help me understand what `Span::mixed_site()` does here? I feel I would write it like this:

```suggestion
    variant_header = quote! { { #variant_header .. }};
```

**Review by frol — APPROVED** [review]
All the blockers were resolved 🚀
